### PR TITLE
Update debian packaging for v3.4.0

### PR DESCRIPTION
**Pull request by who-biz**
Nearly identical commit to https://github.com/EpicCash/epic/pull/94, does the same for epic-wallet.

### CODE REVIEW

**Review by danrmiller — APPROVED** [review]
LGTM

**Comment by who-biz** [comment]
This needs a couple more changes before merge.

Something in `debian/rules` script is causing cargo to update dependencies, and it appears that `epic-wallet` is being built twice. The second time is failing, first appears successful. 

`ctrlc` dependency is being updated to `3.4.0`, rather than our Cargo.toml entry version `3.1`. Versions up to `3.2.4` seem fine. 

Will fix tomorrow. Might as well wait on approvals, unless someone else can spot the issue quickly.

**Comment by who-biz** [comment]
Issue mentioned above has been fixed by requiring cargo to use `Cargo.lock` versions of deps via: `cargo install --locked` in `debian/rules` script.

**Review by skykingisepic — APPROVED** [review]
OK

**Pull request merged**
