### PR TITLE
Epicbox 0.0.2

### PR DESCRIPTION
**Pull request by fastepic**
# Description
Adopt protocol 2.0.0 and FastSend message for push walet to faster PostSlate to epicboxnodejs. Works only with epixbox nodejs version.

## Type of change

-  New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes
Full tested with epicbox.fastepic.eu 
# Relevant notes

### CODE REVIEW

**Comment by fastepic** [comment]
Look out - for EpicboxListenChannel is set var for start Subscription and for EpicboxChannel which works only with command Send  Subscribtion is not set !!!

**Comment by fastepic** [comment]
FastSend message from epicbox is adopt because I don't find method in wallet to make it breaks Mutex lock on read_message websocket. But Rust is not my "native" language so maybe we can remove FastSend message from procole - it only push wallet to faster post_slate.

**Review by johanneshahn — DISMISSED** [review]
This pull request is not compatible with the current epicbox protocol.

1. ProtocolResponse is removed and replaced with a other Version ProtocolResponseV2
2. The subscribe request to create a new session to epicbox is removed. The listener can't send a keep alive to the epicbox. The epicbox diconnects the listener and the listener must restart. This is not required if the listener can send a subscribe request every 60 seconds.

ToDo: enable a fallback for ProtocolResponse when ProtocolResponseV2 is not supported with the used epicbox. Or before making it complicated. Extend epicbox Protocol to handle ProtocolResponseV2
Don't remove the keep-alive to epicbox process.

**Comment by who-biz** [comment]
@johanneshahn Looking into your points now.  Numbered portions below are points/responses. Bullets beneath them are questions/proposed routes of action.

1.) `ProtocolResponse` itself is not removed, just its usage. Existing structs are still in codebase for both versions.

- Provided we intend to adopt these mechanics in our eventual Rust rewrite, I don't see a real reason to keep `ProtocolRequest` and `ProtocolRequestV2` both around.
- If this is really an issue, and we want to preserve the old v1 protocol, we can add a `-v 1||2` flag to `send` command.  
- Alternatively, we can just preserve old functions that use `ProtocolResponse`, clone them into new ones which utilize `ProtocolResponseV2`, and leave V1 there for history's sake.

2.) Subscribe request was relocated to here: https://github.com/EpicCash/epic-wallet/pull/71/files#diff-8a6e898f49ba8c435633efbd97374c1ddf39ab6cc430a54db2a528d1f10d5e2fR823-R835.  With the `reconnection` changes I added, subscribing multiple times is no longer necessary. Listener will no longer disconnect (in a manner that requires a restart to listener) as a result.

- I'm not sure what you're referring to in `keep alive`.  If i'm not understanding please clarify. Wallet never sent a keepalive in the past, to my knowledge.  It's not required any longer either.  Listener will persist until quit manually.

---

Apart from that, I don't see a lot that needs changed.  I'm going to do some testing against the old `epicbox` with v1 Protocol to ensure that running that against this version of wallet doesn't cause crashes.  With the addition of new `version` message, we might be checking against a value that does not exist in message. 

See my comments on commit for other notes.  Mostly regarding log level changes, and I'll go through and improve some of the english for you non-native tongues ;)

**Comment by who-biz** [comment]
> I'm going to do some testing against the old epicbox with v1 Protocol to ensure that running that against this version of wallet doesn't cause crashes. With the addition of new version message, we might be checking against a value that does not exist in message.

Confirmed that old `epicbox` does not cause wallet to crash.  Errors result, but they appear properly handled by `epic-wallet`.

**Comment by johanneshahn** [comment]
I tested the code changes and this version with epicbox rust has some breaking changes in how the wallet and epicbox communicate.

The subcription request is done now in first step, but only once.

To keep the connection to epicbox open (keep-alive), the wallet must send every minute a new subcription request to the epicbox. Else epicbox is dropping the connection with the wallet. And then wallet listener restart kicks in.

Maybe its better to first implement the new protocol message "made" and "version" into epicbox rust before checking further.

**Review by who-biz — APPROVED** [review]

**Comment by who-biz** [comment]
Changed base branch to `epicbox-0.0.2` to indicate V2 Protocol changes atop of `epicbox-0.0.1` branch.

Also cloned `epicbox-0.0.1` branch into a new branch named `gui-wallet` for @johanneshahn's work

**Pull request merged**
